#!/bin/sh


PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/yourpath/fmd.py
NAME=fmd
DESC="fmd web radio"


test -x $DAEMON || exit 0

set -e

case "$1" in
    start)
    	while :; do 
		$DAEMON 
	done &
        ;;
    *)
        echo "Usage: fmd $1 not supported" >&2
        exit 1
        ;;
esac

exit 0
